# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import datanode_pb2 as datanode__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in datanode_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class dataNodeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.WriteBlock = channel.unary_unary(
                '/dataNode/WriteBlock',
                request_serializer=datanode__pb2.WriteBlockRequest.SerializeToString,
                response_deserializer=datanode__pb2.WriteBlockResponse.FromString,
                _registered_method=True)
        self.ReadBlock = channel.unary_unary(
                '/dataNode/ReadBlock',
                request_serializer=datanode__pb2.ReadBlockRequest.SerializeToString,
                response_deserializer=datanode__pb2.ReadBlockResponse.FromString,
                _registered_method=True)
        self.CheckStatus = channel.unary_unary(
                '/dataNode/CheckStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=datanode__pb2.Response.FromString,
                _registered_method=True)
        self.SendIndex = channel.unary_unary(
                '/dataNode/SendIndex',
                request_serializer=datanode__pb2.SendIndexRequest.SerializeToString,
                response_deserializer=datanode__pb2.Sended.FromString,
                _registered_method=True)
        self.ReceiveData = channel.unary_unary(
                '/dataNode/ReceiveData',
                request_serializer=datanode__pb2.ReceiveDataRequest.SerializeToString,
                response_deserializer=datanode__pb2.ReceiveDataResponse.FromString,
                _registered_method=True)


class dataNodeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def WriteBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadBlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReceiveData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_dataNodeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'WriteBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteBlock,
                    request_deserializer=datanode__pb2.WriteBlockRequest.FromString,
                    response_serializer=datanode__pb2.WriteBlockResponse.SerializeToString,
            ),
            'ReadBlock': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadBlock,
                    request_deserializer=datanode__pb2.ReadBlockRequest.FromString,
                    response_serializer=datanode__pb2.ReadBlockResponse.SerializeToString,
            ),
            'CheckStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=datanode__pb2.Response.SerializeToString,
            ),
            'SendIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.SendIndex,
                    request_deserializer=datanode__pb2.SendIndexRequest.FromString,
                    response_serializer=datanode__pb2.Sended.SerializeToString,
            ),
            'ReceiveData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveData,
                    request_deserializer=datanode__pb2.ReceiveDataRequest.FromString,
                    response_serializer=datanode__pb2.ReceiveDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dataNode', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dataNode', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class dataNode(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def WriteBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode/WriteBlock',
            datanode__pb2.WriteBlockRequest.SerializeToString,
            datanode__pb2.WriteBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadBlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode/ReadBlock',
            datanode__pb2.ReadBlockRequest.SerializeToString,
            datanode__pb2.ReadBlockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode/CheckStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            datanode__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode/SendIndex',
            datanode__pb2.SendIndexRequest.SerializeToString,
            datanode__pb2.Sended.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReceiveData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dataNode/ReceiveData',
            datanode__pb2.ReceiveDataRequest.SerializeToString,
            datanode__pb2.ReceiveDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
