# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: datanode.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'datanode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tanode.proto\x1a\x1bgoogle/protobuf/empty.proto\"/\n\x11WriteBlockRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"%\n\x12WriteBlockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\" \n\x10ReadBlockRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x11ReadBlockResponse\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x0c\"D\n\x10SendIndexRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0c\n\x04user\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\"\x1a\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\"\x18\n\x06Sended\x12\x0e\n\x06sended\x18\x01 \x01(\x08\"C\n\x12ReceiveDataRequest\x12\r\n\x05\x62lock\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"&\n\x13ReceiveDataResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x94\x02\n\x08\x64\x61taNode\x12\x37\n\nWriteBlock\x12\x12.WriteBlockRequest\x1a\x13.WriteBlockResponse\"\x00\x12\x34\n\tReadBlock\x12\x11.ReadBlockRequest\x1a\x12.ReadBlockResponse\"\x00\x12\x32\n\x0b\x43heckStatus\x12\x16.google.protobuf.Empty\x1a\t.Response\"\x00\x12)\n\tSendIndex\x12\x11.SendIndexRequest\x1a\x07.Sended\"\x00\x12:\n\x0bReceiveData\x12\x13.ReceiveDataRequest\x1a\x14.ReceiveDataResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'datanode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WRITEBLOCKREQUEST']._serialized_start=47
  _globals['_WRITEBLOCKREQUEST']._serialized_end=94
  _globals['_WRITEBLOCKRESPONSE']._serialized_start=96
  _globals['_WRITEBLOCKRESPONSE']._serialized_end=133
  _globals['_READBLOCKREQUEST']._serialized_start=135
  _globals['_READBLOCKREQUEST']._serialized_end=167
  _globals['_READBLOCKRESPONSE']._serialized_start=169
  _globals['_READBLOCKRESPONSE']._serialized_end=202
  _globals['_SENDINDEXREQUEST']._serialized_start=204
  _globals['_SENDINDEXREQUEST']._serialized_end=272
  _globals['_RESPONSE']._serialized_start=274
  _globals['_RESPONSE']._serialized_end=300
  _globals['_SENDED']._serialized_start=302
  _globals['_SENDED']._serialized_end=326
  _globals['_RECEIVEDATAREQUEST']._serialized_start=328
  _globals['_RECEIVEDATAREQUEST']._serialized_end=395
  _globals['_RECEIVEDATARESPONSE']._serialized_start=397
  _globals['_RECEIVEDATARESPONSE']._serialized_end=435
  _globals['_DATANODE']._serialized_start=438
  _globals['_DATANODE']._serialized_end=714
# @@protoc_insertion_point(module_scope)
